coders= [{"NOMBRE Y APELLIDOS": "AST Alba Azcano Crespo",
        "PROMOCION": "AST",
        "L-BIO": "",
        "L-AST": "x",
        "L-BCN": "",
        "S-JAVASCRIPT": "x",
        "S-VUE": "x",
        "S-JAVA": "",
        "S-PHP": "",
        "S-PYTHON": ""
    },
    {
        "NOMBRE Y APELLIDOS": "AST Ana María Robles Cortés",
        "PROMOCION": "AST",
        "L-BIO": "",
        "L-AST": "x",
        "L-BCN": "",
        "S-JAVASCRIPT": "x",
        "S-VUE": "x",
        "S-JAVA": "",
        "S-PHP": "",
        "S-PYTHON": ""
    },
    {
        "NOMBRE Y APELLIDOS": "AST Caio César da Silva Teixeira",
        "PROMOCION": "AST",
        "L-BIO": "",
        "L-AST": "x",
        "L-BCN": "",
        "S-JAVASCRIPT": "x",
        "S-VUE": "x",
        "S-JAVA": "",
        "S-PHP": "",
        "S-PYTHON": ""
    },
    {
        "NOMBRE Y APELLIDOS": "AST Christian Tomás Bazán Infiestas",
        "PROMOCION": "AST",
        "L-BIO": "",
        "L-AST": "x",
        "L-BCN": "",
        "S-JAVASCRIPT": "x",
        "S-VUE": "x",
        "S-JAVA": "",
        "S-PHP": "",
        "S-PYTHON": ""
    },
    {
        "NOMBRE Y APELLIDOS": "BCN Andrea Ruíz Rull",
        "PROMOCION": "BCN",
        "L-BIO": "",
        "L-AST": "",
        "L-BCN": "x",
        "S-JAVASCRIPT": "",
        "S-VUE": "",
        "S-JAVA": "",
        "S-PHP": "x",
        "S-PYTHON": "x"
    },
    {
        "NOMBRE Y APELLIDOS": "BCN Carmen Rubio Rubio Ortells",
        "PROMOCION": "BCN",
        "L-BIO": "",
        "L-AST": "",
        "L-BCN": "x",
        "S-JAVASCRIPT": "",
        "S-VUE": "",
        "S-JAVA": "",
        "S-PHP": "x",
        "S-PYTHON": "x"
    },
    {
        "NOMBRE Y APELLIDOS": "BCN Cecilia Carbajal Belmont",
        "PROMOCION": "BCN",
        "L-BIO": "",
        "L-AST": "",
        "L-BCN": "x",
        "S-JAVASCRIPT": "",
        "S-VUE": "",
        "S-JAVA": "",
        "S-PHP": "x",
        "S-PYTHON": "x"
    },
    {
        "NOMBRE Y APELLIDOS": "BCN Clàudia Calero Duró",
        "PROMOCION": "BCN",
        "L-BIO": "",
        "L-AST": "",
        "L-BCN": "x",
        "S-JAVASCRIPT": "",
        "S-VUE": "",
        "S-JAVA": "",
        "S-PHP": "x",
        "S-PYTHON": "x"
    },
    
    {
        "NOMBRE Y APELLIDOS": "BIO Ainara Arévalo Palomino",
        "PROMOCION": "BIO",
        "L-BIO": "x",
        "L-AST": "",
        "L-BCN": "",
        "S-JAVASCRIPT": "x",
        "S-VUE": "x",
        "S-JAVA": "",
        "S-PHP": "",
        "S-PYTHON": "x"
    },
    {
        "NOMBRE Y APELLIDOS": "BIO Ainhoa Mendibe Ferreras",
        "PROMOCION": "BIO",
        "L-BIO": "x",
        "L-AST": "",
        "L-BCN": "",
        "S-JAVASCRIPT": "x",
        "S-VUE": "x",
        "S-JAVA": "",
        "S-PHP": "",
        "S-PYTHON": "x"
    },
    {
        "NOMBRE Y APELLIDOS": "BIO Claudio Daniel Gandolffi ",
        "PROMOCION": "BIO",
        "L-BIO": "x",
        "L-AST": "",
        "L-BCN": "",
        "S-JAVASCRIPT": "x",
        "S-VUE": "x",
        "S-JAVA": "",
        "S-PHP": "",
        "S-PYTHON": "x"
    },
    {
        "NOMBRE Y APELLIDOS": "BIO David Ordiales Fernández",
        "PROMOCION": "BIO",
        "L-BIO": "x",
        "L-AST": "",
        "L-BCN": "",
        "S-JAVASCRIPT": "x",
        "S-VUE": "x",
        "S-JAVA": "",
        "S-PHP": "",
        "S-PYTHON": "x"}]

recruiters=[{"EMPRESA": "AST-ABAMobile",
        "NOMBRE DEL RECRUITER": "Laura Selina SÁNCHEZ",
        "EMAIL": "-",
        "CARGO": "Administracion y RRHH",
        "LINKEDIN": "https://www.linkedin.com/in/laura-selina-s-6ab10120a/",
        "L-BCN": "",
        "L-AST": "X",
        "L-BIO": "",
        "S-PHP": "X",
        "S-JAVA": "X",
        "S-PYTHON": "X",
        "10:10": "x",
        "10:20": "x",
        "10:30": "x",
        "10:40": "x",
        "10:50": "x",
        "11:00": "x",
        "11:20": "x",
        "11:30": "x",
        "11:40": "x",
        "11:50": "x",
        "12:00": "x",
        "12:10": "x",
        "12:30": "x",
        "12:40": "x",
        "12:50": "x"
    },
    {
        "EMPRESA": "BCN-Accenture",
        "NOMBRE DEL RECRUITER": "Samantha CRISTOBAL",
        "EMAIL": "-",
        "CARGO": "Talent Acquisition",
        "LINKEDIN": "https://www.linkedin.com/in/samantha-cristobal-6a6154221/",
        "L-BCN": "X",
        "L-AST": "",
        "L-BIO": "",
        "S-PHP": "",
        "S-JAVA": "X",
        "S-PYTHON": "X",
        "10:10": "x",
        "10:20": "x",
        "10:30": "x",
        "10:40": "x",
        "10:50": "x",
        "11:00": "x",
        "11:20": "x",
        "11:30": "x",
        "11:40": "x",
        "11:50": "x",
        "12:00": "x",
        "12:10": "",
        "12:30": "",
        "12:40": "",
        "12:50": ""
    },
    {
        "EMPRESA": "Alisys",
        "NOMBRE DEL RECRUITER": "Andrés ALVAREZ CORTÉS",
        "EMAIL": "-",
        "CARGO": "Técnico de RRHH",
        "LINKEDIN": "https://www.linkedin.com/in/paloma-gonz%C3%A1lez-fern%C3%A1ndez-93b945173/?originalSubdomain=es",
        "L-BCN": "X",
        "L-AST": "X",
        "L-BIO": "",
        "S-PHP": "X",
        "S-JAVA": "X",
        "S-PYTHON": "",
        "10:10": "x",
        "10:20": "x",
        "10:30": "x",
        "10:40": "x",
        "10:50": "x",
        "11:00": "x",
        "11:20": "x",
        "11:30": "x",
        "11:40": "x",
        "11:50": "x",
        "12:00": "x",
        "12:10": "x",
        "12:30": "x",
        "12:40": "x",
        "12:50": "x"
    },
    {
        "EMPRESA": "Claire Joster (Grupo Eurofirms)",
        "NOMBRE DEL RECRUITER": "Oihane ANTOLÍN REYES",
        "EMAIL": "-",
        "CARGO": "Consultora IT",
        "LINKEDIN": "https://www.linkedin.com/in/oihanean/",
        "L-BCN": "",
        "L-AST": "",
        "L-BIO": "X",
        "S-PHP": "X",
        "S-JAVA": "X",
        "S-PYTHON": "X",
        "10:10": "x",
        "10:20": "x",
        "10:30": "x",
        "10:40": "x",
        "10:50": "x",
        "11:00": "x",
        "11:20": "x",
        "11:30": "x",
        "11:40": "x",
        "11:50": "x",
        "12:00": "x",
        "12:10": "x",
        "12:30": "x",
        "12:40": "x",
        "12:50": "x"
    },
    {
        "EMPRESA": "BIO-D&A Innovative Systems",
        "NOMBRE DEL RECRUITER": "ALBERTO BLAZQUEZ",
        "EMAIL": "-",
        "CARGO": "CEO",
        "LINKEDIN": "https://www.linkedin.com/in/ablazquez/",
        "L-BCN": "",
        "L-AST": "",
        "L-BIO": "X",
        "S-PHP": "X",
        "S-JAVA": "X",
        "S-PYTHON": "",
        "10:10": "x",
        "10:20": "x",
        "10:30": "x",
        "10:40": "x",
        "10:50": "x",
        "11:00": "x",
        "11:20": "x",
        "11:30": "x",
        "11:40": "x",
        "11:50": "x",
        "12:00": "x",
        "12:10": "x",
        "12:30": "x",
        "12:40": "x",
        "12:50": "x"
    },
    {
        "EMPRESA": "Devoteam Drago",
        "NOMBRE DEL RECRUITER": "IGNACIO MERINO ALVAREZ",
        "EMAIL": "-",
        "CARGO": "DIRECTOR ZONA NORTE",
        "LINKEDIN": "https://www.linkedin.com/in/ignacio-merino/",
        "L-BCN": "X",
        "L-AST": "",
        "L-BIO": "X",
        "S-PHP": "X",
        "S-JAVA": "X",
        "S-PYTHON": "X",
        "10:10": "x",
        "10:20": "x",
        "10:30": "x",
        "10:40": "x",
        "10:50": "x",
        "11:00": "x",
        "11:20": "x",
        "11:30": "x",
        "11:40": "x",
        "11:50": "x",
        "12:00": "x",
        "12:10": "x",
        "12:30": "x",
        "12:40": "x",
        "12:50": "x"
    },
    {
        "EMPRESA": "BIO-Worköholics",
        "NOMBRE DEL RECRUITER": "Laura CARAZO",
        "EMAIL": "-",
        "CARGO": "CEO",
        "LINKEDIN": "https://www.linkedin.com/in/lauracarazo/",
        "L-BCN": "",
        "L-AST": "",
        "L-BIO": "X",
        "S-PHP": "",
        "S-JAVA": "",
        "S-PYTHON": "",
        "10:10": "x",
        "10:20": "x",
        "10:30": "x",
        "10:40": "x",
        "10:50": "x",
        "11:00": "x",
        "11:20": "x",
        "11:30": "x",
        "11:40": "x",
        "11:50": "x",
        "12:00": "x",
        "12:10": "x",
        "12:30": "x",
        "12:40": "x",
        "12:50": "x"
    },
    {
        "EMPRESA": "BIO-Zorraquino",
        "NOMBRE DEL RECRUITER": "Jon BARRAGAN BALLESTA",
        "EMAIL": "-",
        "CARGO": "Responsable Desarollo",
        "LINKEDIN": "https://www.linkedin.com/in/jonbarragan/",
        "L-BCN": "",
        "L-AST": "",
        "L-BIO": "X",
        "S-PHP": "X",
        "S-JAVA": "",
        "S-PYTHON": "",
        "10:10": "x",
        "10:20": "x",
        "10:30": "x",
        "10:40": "x",
        "10:50": "x",
        "11:00": "x",
        "11:20": "x",
        "11:30": "x",
        "11:40": "x",
        "11:50": "x",
        "12:00": "x",
        "12:10": "x",
        "12:30": "x",
        "12:40": "x",
        "12:50": "x"}]